# Generated by Django 5.2.6 on 2025-09-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0004_comment'),
    ]

    operations = [
    ]
